version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    env_file: ./.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    container_name: container_name
